### ISSUE TITLE
Doesn't work with findbugs 3

### ISSUE THREAD

**Issue by ctubbsii** [overstock/library-detectors#3]
Tried this with findbugs-maven-plugin 3.0.3 and it didn't work:

```
[INFO] Fork Value is true
     [java] Exception in thread "main" java.lang.ExceptionInInitializerError
     [java] 	at edu.umd.cs.findbugs.DetectorFactoryCollection.getCoreResource(DetectorFactoryCollection.java:392)
     [java] 	at edu.umd.cs.findbugs.SystemProperties.loadPropertiesFromConfigFile(SystemProperties.java:77)
     [java] 	at edu.umd.cs.findbugs.SystemProperties.<clinit>(SystemProperties.java:60)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.<clinit>(FindBugs2.java:86)
     [java] Caused by: java.lang.IllegalStateException: Unable to load core plugin
     [java] 	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1475)
     [java] 	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1425)
     [java] 	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:154)
     [java] 	... 4 more
     [java] Caused by: edu.umd.cs.findbugs.PluginDoesntContainMetadataException: Core pluginfindbugs-3.0.1.jar doesn't contain findbugs.xml; ...
     [java] 	at edu.umd.cs.findbugs.PluginLoader.getPluginDescriptor(PluginLoader.java:1172)
     [java] 	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:653)
     [java] 	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:400)
     [java] 	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1471)
     [java] 	... 6 more
```

**Comment by ctubbsii** [comment]
This looks like it could be the same issue as tim-group/test-driven-detectors4findbugs#26

**Comment by ctubbsii** [comment]
Sorry, I'm wrong. I configured the plugin poorly. The proper way is to do it like this:

```xml
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>findbugs-maven-plugin</artifactId>
          <version>${findbugs.version}</version>
          <configuration>
            <xmlOutput>true</xmlOutput>
            <effort>Max</effort>
            <failOnError>true</failOnError>
            <includeTests>true</includeTests>
            <maxRank>16</maxRank>
            <plugins>
              <plugin>
                <groupId>com.overstock.findbugs</groupId>
                <artifactId>library-detectors</artifactId>
                <version>1.1</version>
              </plugin>
            </plugins>
          </configuration>
        </plugin>
```

It would be helpful to document this.
